### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by jimmyfyx** [NagabhushanSN95/DeCOMPnet#2]
Hi,

I met this error when trying to run `VeedDynamicTester01.py` and I'm not sure how to solve it:

> CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)` 
Traceback (most recent call last):
  File "VeedDynamicTester01.py", line 474, in <module>
    main()
  File "VeedDynamicTester01.py", line 460, in main
    demo1()
  File "VeedDynamicTester01.py", line 97, in demo1
    start_testing(train_configs, test_configs)
  File "VeedDynamicTester01.py", line 20, in start_testing
    output_dirpath = Tester.start_testing(train_configs, test_configs, save_intermediate_results=False)                                                                                     
  File "/home/yixiaof2/DeCOMPnet/src/Tester01.py", line 283, in start_testing
    pred_frames, masks, extras = tester.predict_next_frame2(video_name, seq_num, pred_frame_num,                                                                                            
  File "/home/yixiaof2/DeCOMPnet/src/Tester01.py", line 101, in predict_next_frame2
    pred_frames, pred_frames_mask, extras = self.predict_next_frame1(input_dict, return_intermediate_results)                                                                               
  File "/home/yixiaof2/DeCOMPnet/src/Tester01.py", line 84, in predict_next_frame1
    output_batch = self.frame_predictor(input_batch, return_intermediate_results)
  File "/home/yixiaof2/.conda/envs/decomp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl                                                                  
    result = self.forward(*input, **kwargs)
  File "/home/yixiaof2/DeCOMPnet/src/frame_predictors/FramePredictor01.py", line 60, in forward                                                                                             
    warper_outputs = self.warper.forward_warp_frame2mpi(warper_inputs)
  File "/home/yixiaof2/DeCOMPnet/src/utils/WarperPytorch.py", line 28, in forward_warp_frame2mpi                                                                                            
    trans_points12 = self.compute_transformed_points(depth1a, input_batch['transformation1'],
  File "/home/yixiaof2/DeCOMPnet/src/utils/WarperPytorch.py", line 62, in compute_transformed_points                                                                                        
    transformation = torch.bmm(transformation2, torch.linalg.inv(transformation1))  # (b, 4, 4)                                                                                             
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

I also searched online and in this forum someone mentions the possibility of dimension mismatch:
https://discuss.pytorch.org/t/runtimeerror-cuda-error-cublas-status-invalid-value-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/124544/5

Thanks!

**Comment by NagabhushanSN95** [comment]
Hi,
I am unable to reproduce this in my setup, and I don't see why this should cause a shape mismatch error. Can you print the shape of `transformation1` and `transformation2` before this line and share the log?

**Comment by jimmyfyx** [comment]
Ah yes here is the updated log with the shape printed:

> Program started at 09/10/2023 01:11:41 AM
/home/yixiaof2/DeCOMPnet/Weights/FlowEstimation/Model_Iter010000.tar
Loaded Model /home/yixiaof2/DeCOMPnet/Weights/FlowEstimation/Model_Iter010000.tar trained for 10000 iterations                                                                              
Loaded Model /home/yixiaof2/DeCOMPnet/Weights/VideoInpainting/Model_Iter010000.tar trained for 10000 iterations                                                                             
Testing begins for Test0001
  0%|                                                                                                                                                                | 0/520 [00:00<?, ?it/s]
torch.Size([1, 4, 4])
torch.Size([1, 4, 4])
  0%|                                                                                                                                                                | 0/520 [00:01<?, ?it/s]
CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)` 
Traceback (most recent call last):
  File "VeedDynamicTester01.py", line 474, in <module>
    main()
  File "VeedDynamicTester01.py", line 460, in main
    demo1()
  File "VeedDynamicTester01.py", line 97, in demo1
    start_testing(train_configs, test_configs)
  File "VeedDynamicTester01.py", line 20, in start_testing
    output_dirpath = Tester.start_testing(train_configs, test_configs, save_intermediate_results=False)                                                                                     
  File "/home/yixiaof2/DeCOMPnet/src/Tester01.py", line 283, in start_testing
    pred_frames, masks, extras = tester.predict_next_frame2(video_name, seq_num, pred_frame_num,                                                                                            
  File "/home/yixiaof2/DeCOMPnet/src/Tester01.py", line 101, in predict_next_frame2
    pred_frames, pred_frames_mask, extras = self.predict_next_frame1(input_dict, return_intermediate_results)                                                                               
  File "/home/yixiaof2/DeCOMPnet/src/Tester01.py", line 84, in predict_next_frame1
    output_batch = self.frame_predictor(input_batch, return_intermediate_results)
  File "/home/yixiaof2/.conda/envs/decomp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl                                                                  
    result = self.forward(*input, **kwargs)
  File "/home/yixiaof2/DeCOMPnet/src/frame_predictors/FramePredictor01.py", line 60, in forward                                                                                             
    warper_outputs = self.warper.forward_warp_frame2mpi(warper_inputs)
  File "/home/yixiaof2/DeCOMPnet/src/utils/WarperPytorch.py", line 28, in forward_warp_frame2mpi                                                                                            
    trans_points12 = self.compute_transformed_points(depth1a, input_batch['transformation1'],
  File "/home/yixiaof2/DeCOMPnet/src/utils/WarperPytorch.py", line 64, in compute_transformed_points                                                                                        
    transformation = torch.bmm(transformation2, torch.linalg.inv(transformation1))  # (b, 4, 4)                                                                                             
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
Program ended at 09/10/2023 01:11:45 AM
Execution time: 0:00:03.036073

**Comment by NagabhushanSN95** [comment]
Thanks. As you can see, there is no mismatch in the shape. It appears that there can be multiple reasons for which CUBLAS_STATUS_NOT_SUPPORTED would be thrown. Can you try running the code on a different machine?

I lost my setup when we formatted our workstations recently. Since I'm not actively working on this, I will need a few days to set it up on my workstation. However, I am positive that this code worked in my previous setup. Please double-check to ensure the package versions are matching. Changes in PyTorch or other dependent packages might be causing this issue.

**Comment by jimmyfyx** [comment]
OK, thanks! I will try.

**Comment by jimmyfyx** [comment]
Thanks the problem has been solved by switching to another machine. Indeed there might be some problems on my machine, but I'm still not too sure what triggers this error.

**Comment by NagabhushanSN95** [comment]
Great! Glad to know it worked out. I will close this issue.
